### ISSUE TITLE
[Output Image Not Correct]  Problems of Landmark Detector

### ISSUE THREAD

**Issue by SonPH088** [ramgendeploy/headswap-machine#2]
Hi Ramgen, 

it's me again :v: 

I'm have been working on your project for a days, but no luck to get the perfect image result.
I can not move the source mask and the crop face into place to make the composition with the headless template.

Maybe the problems is in function : "transformation_from_points":

def transformation_from_points(points1, points2):
    points1 = points1.astype(np.float32)
    points2 = points2.astype(np.float32)

    c1 = np.mean(points1, axis=0)
    c2 = np.mean(points2, axis=0)
    points1 -= c1
    points2 -= c2

    s1 = np.std(points1)
    s2 = np.std(points2)
    points1 /= s1
    points2 /= s2

    U, S, Vt = np.linalg.svd(points1.T * points2)
    R = (U * Vt).T

    return np.vstack([np.hstack(((s2 / s1) * R,
                                 c2.T - (s2 / s1) * R * c1.T)),
                      np.matrix([0., 0., 1.])])

Could you please explain for me how it work and how to get the perfect result?
Thank you!

![test_result](https://user-images.githubusercontent.com/81842098/114011236-3614a500-988f-11eb-85d2-78958da556fd.jpg)

**Comment by ramgendeploy** [comment]
Hey glad that you could get an output.
mh maybe it's the landmark detector, check how many faces it detects, sometimes it fails and detects smaller faces in the image.
Can you give me a link to the inputs I'll try them out and see what's failing.

Here it's a colab so you can prototype better:
https://colab.research.google.com/drive/1o3C92DuLKe92g6usNRiIS9jZbaWWKsNN

The Headless template it's supposed to not have the head, you can remove that with photoshop, but the idea is to use a filler Model but I didn't implement that yet.

Another thing, the style transfer, and color transfer are optional if you want to get a more natural result.

With regards to the function, it's fine, the issue is the inputs, more than sure the face landmark detector failed to get the correct face.

**Comment by SonPH088** [comment]
Hi Ramgen!

Thanks for confirm about the problems, i will dig into landmark detector to find out what am i doing wrong.

The input images that i used is random images from internet or you can take my results from the attached file bellow.

I would like to try your prototype on Colab and sent the request access. Could you please accept my request?

About the style transfer and color transfer, i will learn about it after get throw this problems.

Thank you so much!

-------------------------------------------------------------------
[image_test.zip](https://github.com/ramgendeploy/headswap-machine/files/6283666/image_test.zip)

[test_result.zip](https://github.com/ramgendeploy/headswap-machine/files/6283909/test_result.zip)

**Comment by ramgendeploy** [comment]
Oh my bad I forgot to put it in public, it should work now.
No problem, I'll try the inputs and see what's failing.

**Comment by ramgendeploy** [comment]
Hey @SonPH088 
I tested the images in the colab that I sent you and this is the result.
![final_image](https://user-images.githubusercontent.com/33965345/114480301-b3fee600-9bd8-11eb-8be7-3b6024a307c2.jpg)
So the notebook code is working as expected.

Maybe there is some code in the repo that is wrong, maybe I made a mistake when I was refactoring things.
If you find something wrong in the repo's code let me know.
I'll try to find the issue, to be honest, a lot of things need a big refactor 😂

**Comment by SonPH088** [comment]
Hi @ramgendeploy,

Sorry for the delay reply. 

I am able to access and run the code on your Colab. The result is good.
I'm also compared your notebook code and code in the repo. Turn out, the problem is calling 'landmarks' function. 

In line 61, swaplib/matrixTransfer/dotheswap.py : 

  lm = landmarks([source_path, ref_path])

it should be :  

  lm = landmarks(['./crop_source.jpg', ref_path]) 

And the head will be on the right position :vampire: 
Could you make change repo to everyone can avoid my issue. 

Then, I will try to style transfer and color transfer. 
Hope you can help me more in the future :+1: 

Thanks!

**Comment by ramgendeploy** [comment]
Hey @SonPH088 
Issue has been resolved,
the problem was that in the repo it was processing the landmarks of the original image and not the cropface,
I solve it and it should be working now.

Some more info about the repo:
The headless template should not have a face, this can be done with an image inpainting model, 
I need to find a good model for this.
I did one manually in the test folder using PS.
Also, I want to make a wiki section in the repo, to explain the functions in the repo.

If you find any more bugs don't hesitate to make a new issue.
